name: 'Create Jira issues'
author: Rick Meneely <rick@meneely.com>
branding:
  icon: star
  color: blue
description: Creates Jira issues specified via a JSON file"
inputs:
  input:
    description: input file specifying Jira issues (JSON)
    default: 'issues.json'
    required: false
  url:
    description: The base URL (e.g. http://myjira.atlassian)
    default: ''
    required: true
  user_email:
    description: The Jira user email
    default: ''
    required: true
  api_token:
    description: The Jira API token
    default: ''
    required: true
outputs:
  issues:
    description: 'Returns a comma separated list of created issues'
    value: ${{ steps.create-jira-issues.outputs.issues }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
      working-directory: ${{ github.action_path }}
      shell: bash
    - id: create-jira-issues
      run: |
        python ${{ github.action_path }}/create-jira-issues.py \
          --input "${{ inputs.input }}" \
          --url "${{ inputs.url }}" \
          --user_email "${{ inputs.user_email }}" \
          --api_token "${{ inputs.api_token }}"
      shell: bash
